In [2]:
import gym 
import numpy as np

In [3]:
env = gym.make('FrozenLake-v0')

[2017-05-16 15:58:10,372] Making new env: FrozenLake-v0


In [6]:
env.observation_space.n

16

In [8]:
env.action_space.n

4

In [9]:
Q = np.zeros([env.observation_space.n, env.action_space.n])

## Learing parameters 
lr = 0.85
y =  0.99 
num_episodes = 2000
rList = []
for i in range(num_episodes):
    s = env.reset()
    rAll = 0 
    d = False
    j = 0 
    #The Q learning algorithm 
    while j < 99 :
        j += 1
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        ## get new state and reward from the environment 
        s1,r,d,_ = env.step(a)
        Q[s,a] = Q[s,a] + lr * (r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
        rList.append(rAll)
    

In [11]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.0


In [15]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  6.73229184e-03   3.91304781e-01   8.93897412e-03   1.03481454e-02]
 [  1.26975144e-03   2.55076179e-03   9.23452818e-04   2.39307232e-01]
 [  2.77643212e-03   5.10983220e-03   1.71535621e-03   1.51828050e-01]
 [  1.05610763e-03   1.06338192e-03   0.00000000e+00   1.10585619e-01]
 [  6.04627848e-01   1.08705797e-03   3.94080821e-04   2.54145806e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  6.39558836e-04   6.44222834e-05   3.29352364e-04   7.93322139e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.06310072e-03   0.00000000e+00   3.87749085e-05   7.72198953e-01]
 [  4.10371847e-04   2.42894094e-01   0.00000000e+00   0.00000000e+00]
 [  6.31698757e-04   7.67203660e-05   2.60682961e-02   4.72769275e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   9.54287985e-01   0